spring:
  datasource:
    url: jdbc:h2:mem:company-training
  driverClassName: org.h2.Driver
  username: sa
  password:
  h2:
    console:
      enabled: true
  flyway:
    baseline-on-migrate: true
  jpa:
    generate-ddl: false
